# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zJTTAf7cpymwQ6Dr70SMB3XYllOw-mZ
"""

import pandas as pd
teacher=pd.DataFrame ({

      'FISH':['Xalilov D.a','Xontorayev S.I','Jorayeva G.F','Turdimatov M.M','Abdullayeva M.R','Arabboyev A.A','Djalilov M.L','Aloydinov M.G','Qadamova Z.E' ],
      'utish darsi':['suniy intilekt asoslari','Malumotlar tuzilmasi','Elektronika','Kiberxavfsizlik asoslari','Malumotlar tuzilmasi','Kiberxavfsizlik asoslari','Kompyuterni tashkil etish','Kompyuterni tashkil etish','suniy intilekt asoslari'],
        'fan yunalish turi':['maruza','maruza','maruza','maruza','amaliy','amaliy','maruza','amaliy','amaliy'],






})
print(teacher)

teacher.to_exel('teacher.xlsx', index=False, sheet_name='sheet1')